import type { Metadata } from "next";
import "./globals.css";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ClerkProvider, RedirectToSignIn, SignedIn, SignedOut } from '@clerk/nextjs'
import { dmMono, dmSans, geistMono, geistSans, inter, roboto, roboto_mono } from "@/lib/font-styles";
import { Toaster } from "sonner";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} font-inter ${dmMono.variable} ${dmSans.variable}  ${geistMono.variable} ${inter.variable} ${roboto_mono.variable} ${roboto.variable} antialiased`}
        >
          <SignedIn>
            <TooltipProvider>
              {children}
              <Toaster />
            </TooltipProvider>
          </SignedIn>

          <SignedOut>
            <RedirectToSignIn />
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
